language: cpp
compiler:
  - gcc
  - clang
script: ./configure && make test
before_install:
  - git submodule update --init --recursive
  - sudo apt-get install gyp
branches:
  only:
    - master
notifications:
  recipients:
    - z@apiary.io
  email:
    on_success: change
    on_failure: always
